import React from 'react';
import { BoxDiv,Tagline } from '../styledComponents/StyledLegal';
import Footer from '../navigations/Footer';
import Navbar from '../navigations/Navbar';
import { Typography} from '@material-ui/core';

const Terms = () => {
  return (
    <React.Fragment>
    <Navbar />
    <BoxDiv>
      <Tagline style={{fontFamily: 'Roboto'}}>Privacy Policy</Tagline>
 
      <h2> Effective Date: August 25, 2020</h2>
      Encor ("us", "we", or "our") operates the encor.cc website (the "Service"). This page informs you of our policies
      regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have 
      associated with that data. We use your data to provide and improve the Service. By using the Service, you agree to 
      the collection and use of information in accordance with this policy.Unless otherwise defined in this Privacy Policy, 
      terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.

      <h2> Definitions</h2>
      <u>Service:</u> Service is the the website encor.cc and it’s features that it offers users
      <br/><br/>
      <u>Personal Data:</u> Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
      <br/><br/>
      <u>Usage Data:</u> Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
      <br/><br/>
      <u>Cookies:</u> Cookies are small pieces of data stored on your device (computer or mobile device).
      <br/><br/>
      <u>Data Controller:</u> Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.
      <br/><br/>
      <u>Data Processors (or Service Providers):</u> Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.
      <br/><br/>
      <u>Data Subject (or User):</u> Data Subject is any living individual who is using our Service and is the subject of Personal Data.
      <br/><br/>
      <u>Information Collection and Use:</u> We collect several different types of information for various purposes to provide and improve our Service to you.
 

      <h2>Types of Data Collected</h2>
      <u>Personal Data:</u> While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). 
      Personally identifiable information may include, but is not limited to:<br/>
      <ol type='1'>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Social media URLs or Usernames</li>
        <li>Credit Card expiration/type/name</li>
        </ol>
      We may use your Personal Data to contact you with newsletters, marketing or promotional materials 
      and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by 
      following the unsubscribe link or instructions provided in any email we send or by contacting us via email helloencor@gmail.com
      <br/><br/>
      <u>Usage Data:</u> We may also collect information how the Service is accessed and used ("Usage Data"). This Usage Data may include 
      information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service
      that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
      Your IP address is never stored in our database, we use your IP to obtain general and anonymised data about your profile end users such
      as approximate geo-location e.g country, city.
      <br/><br/>
      <u>Location Data:</u> We may use and store information about your location if you give us permission to do so (“Location Data”). 
      We use this data to provide features of our Service, to improve and customize our Service. We may use and store information about visitors
      to Encor Profiles. This is anonymised and aggregated in high quantities, removing any Personally Identifiable information as we are 
      interested in the ‘how’ more than the ‘who’.
      <br/><br/>
      <u>Tracking Cookies Data: </u> We use cookies and similar tracking technologies to track the activity on our Service and hold certain
      information. Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your 
      browser from a website and stored on your device. Tracking technologies also used are, tags, and scripts to collect and track information
      and to improve and analyze our Service. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.
      However, if you do not accept cookies, you may not be able to use some portions of our Service.
      <br/>
      Examples of Cookies we use:
      <ol type='1'>
        <li>Session Cookies: We use Session Cookies to operate and retain user authentication with the service.</li>
        <li>Preference Cookies: We use Preference Cookies to remember your preferences and acceptance of our policies.</li>
        <li>Analytics Cookies: Google/Facebook analytics.</li>
      </ol>
      More information on our use of cookies can be found on our Cookies Policy.


      <h2>Use of Data</h2>
      Encor operating Encor.cc uses the collected data for various purposes:
      <ol type='1'>
        <li>To provide and maintain our Service.</li>
        <li>To notify you about changes to our Service</li>
        <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
        <li>To provide customer support</li>
        <li>To gather analysis or valuable information so that we can improve our Service</li>
        <li>To monitor the usage of our Service</li>
        <li>To detect, prevent and address technical issues</li>
      </ol>
      To provide you with news, special offers and general information about other goods, services and events which we offer that are 
      similar to those that you have already purchased or enquired about unless you have opted not to receive such information

      <h2>Retention of Data</h2> 
      Encor will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.
      We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example,
      if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
      Encor will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except
      when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain
      this data for longer time periods.


      <h2>Transfer of Data</h2>
      Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province,
      country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.
      If you are located outside of Europe and choose to provide information to us, please note that we transfer the data, including Personal
      Data, to The United States of America and process it there. Encor is operated out of an office in Canada. Whilst all servers and data 
      is stored in the United States of America, we are executing the processing and security of data from Canadian personnel. Your consent 
      to this Privacy Policy followed by your submission of such information represents your agreement to that transfer. Encor will take all 
      steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of
      your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security
      of your data and other personal information.

      <h2>Disclosure of Data</h2>
      <u>Business Transaction:</u>  If Bolster Creative PTY LTD is involved in a merger, acquisition or asset sale, your Personal
      Data may be transferred. We will provide notice when your Personal Data is transferred and becomes subject to a different Privacy Policy.
      <br/><br/>
      <u>Disclosure for Law Enforcement:</u> Under certain circumstances, Bolster Creative PTY LTD may be required to disclose your Personal
      Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
      <br/><br/>
      <u>Legal Requirements:</u> Bolster Creative PTY LTD may disclose your Personal Data in the good faith belief that such action is
      necessary to:
      <ol type='1'>
        <li>To comply with a legal obligation</li>
        <li>To protect and defend the rights or property of Bolster Creative PTY LTD</li>
        <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
        <li>To protect the personal safety of users of the Service or the public</li>
        <li>To protect against legal liability</li>
      </ol>

      <h2>Service Providers</h2>
      We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf,
      to perform Service-related services or to assist us in analyzing how our Service is used. These third parties have access to your Personal
      Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
      <br/><br/>
      <u>Analytics:</u> We may use third-party Service Providers to monitor and analyze the use of our Service.
      <ol type='1'>
        <li>Google Analytics: Google Analytics is a web analytics service offered by Google that tracks and reports website traffic.
        Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services.
        Google may use the collected data to contextualize and personalize the ads of its own advertising network. 
        You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics 
        opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information
        with Google Analytics about visits activity. For more information on the privacy practices of Google, please visit the Google Privacy 
        Terms web page: http://www.google.com/intl/en/policies/privacy/
        </li>
      </ol>
      <u>Behavioral Remarketing:</u>Encor uses remarketing services to advertise on third party websites to you after you visited our Service.
      Our third-party vendors use cookies to inform, optimize and serve ads based on your past visits to our Service.
      <ol type='1'>
        <li>Google AdWords: Google AdWords remarketing service is provided by Google Inc. You can opt-out of Google Analytics
        for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page:
        http://www.google.com/settings/ads For more information on the privacy practices of Google, please visit the Google Privacy Terms
        web page: http://www.google.com/intl/en/policies/privacy/
        </li>
        <li>Facebook: Facebook remarketing service is provided by Facebook Inc.  You can learn more about interest-based advertising
        from Facebook by visiting this page: https://www.facebook.com/help/164968693837950 To opt-out from Facebook's interest-based
        ads follow these instructions from Facebook: https://www.facebook.com/help/568137493302217 Facebook adheres to the Self-Regulatory
        Principles for Online Behavioural Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook
        and other participating companies through the Digital Advertising Alliance in the USA http://www.aboutads.info/choices/, the Digital 
        Advertising Alliance of Canada in Canada http://youradchoices.ca/ or the European Interactive Digital Advertising Alliance in Europe
        http://www.youronlinechoices.eu/, or opt-out using your mobile device settings. For more information on the privacy practices of Facebook,
        please visit Facebook's Data Policy: https://www.facebook.com/privacy/explanation</li>
      </ol>
      <u>Payments:</u> We may provide paid products and/or services within the Service. In that case, we use third-party 
      services for payment processing (e.g. payment processors). We will not store or collect your payment card details. 
      That information is provided directly to our third-party payment processors whose use of your personal information is governed by 
      their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council,
      which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure
      handling of payment information. The payment processors we work with are:
      <ol type='1'>
        <li>Stripe: Their Privacy Policy can be viewed at https://stripe.com/us/privacy</li>
      </ol>
      <h2>Security of Data</h2>
      The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic
      storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its
      absolute security.

      <h2>"Do Not Track" Signals</h2>
      We do not support Do Not Track ("DNT"). Do Not Track is a preference you can set in your web browser to inform websites 
      that you do not want to be tracked.You can enable or disable Do Not Track by visiting the Preferences or Settings 
      page of your web browser.

      <h2>Links to Other Sites</h2>
      Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to 
      that third party's site. We highly advise you to review the Privacy Policy of every site you visit. We have no control over and assume 
      no responsibility for the content, privacy policies or practices of any third party sites or services.

      <h2>Encor profiles</h2>
      Encor profiles are populated by the user’s who built the profile. Any links, images, websites, or text are not operated
      by encor and encor is not liable for anything you may click on.

      <h2>Changes to This Privacy Policy</h2>
      We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
      We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective
      date" at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this 
      Privacy Policy are effective when they are posted on this page.

      <h2>Contact us</h2>
      If you have any questions about this Privacy Policy, please contact us at: helloencor@gmail.com


    </BoxDiv>
    <Footer />
    </React.Fragment>
  )
}
      
export default Terms